version: '3'

services:
  my-app:
    build: .
    ports:
      - 3000:3000
    environment:
     - MONGO_DB_USERNAME_FILE=/run/secrets/mongo_db_username
     - MONGO_DB_PWD_FILE=/run/secrets/mongo_db_pwd
    secrets:
      - mongo_db_username
      - mongo_db_pwd

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo_db_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_db_pwd
    secrets:
      - mongo_db_username
      - mongo_db_pwd

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME_FILE=/run/secrets/mongo_db_username
      - ME_CONFIG_MONGODB_ADMINPASSWORD_FILE=/run/secrets/mongo_db_pwd
      - ME_CONFIG_MONGODB_SERVER=mongodb
    secrets:
      - mongo_db_username
      - mongo_db_pwd
    depends_on:
      - "mongodb"

secrets:
  mongo_db_username:
    external: true
  mongo_db_pwd:
    external: true